import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const theme = {
  //   token: {
  //     colorPrimary: '#FF6F61', // Primary accent color (Soft Coral)
  //     colorLink: '#5A6B8E', // Link color (Medium Slate Blue)
  //     colorSuccess: '#4CAF50', // Success color (Soft Green)
  //     colorError: '#E74C3C', // Error color (Soft Red)
  //     colorWarning: '#FF9800', // Warning color
  //     colorTextBase: '#333333', // General text color (Charcoal Gray)
  //     colorTextSecondary: '#2F3A46', // Secondary text color (Slate Gray)
  //     colorBgBase: '#F5F5F5', // Background color (Off-White)
  //     colorBgCard: '#E8E8E8', // Card background (Light Gray)
  //     colorBorder: '#D1D5DB', // Border color (Light Slate Gray)
  //     colorBtnPrimaryBg: '#FF6F61', // Button background (Soft Coral)
  //     colorBtnPrimaryHoverBg: '#FF8C72', // Button hover color (Light Coral)
  //     colorDisabled: '#B0B0B0', // Disabled color (Light Gray)
  //   },
  // };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
