import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ConfigProvider } from 'antd';
import { AntdRegistry } from '@ant-design/nextjs-registry';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = {
    token: {
      // Primary brown accent color
      colorPrimary: '#6F4F1E',

      // Background colors
      colorBgBase: '#F4E1C1',
      colorBgLayout: '#F4E1C1',
      colorBgContainer: '#F4E1C1',

      // Text colors
      colorTextBase: '#5C4033',
      colorTextHeading: '#3E2A47',

      // Link colors
      colorLink: '#8B5E3C',

      // Border colors
      colorBorder: '#D1B2A1',
      colorBorderSecondary: '#D1B2A1',

      // Button colors
      colorBtnPrimary: '#6F4F1E',
      colorBtnPrimaryHover: '#8B4513',

      // Notification and feedback colors
      colorError: '#E74C3C', // For error messages, icons, etc.
      colorSuccess: '#27AE60', // For success messages

      // Other UI elements
      colorTextSecondary: '#8B5E3C', // Muted secondary text
    },
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <ConfigProvider theme={theme}>{children}</ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
